[Host]
description="svnsrv router table toml feature"
author="Force Charlie"
update=2015-12-09T15:19:00Z
address="192.168.1.12"
port=3690
version=1
subver=0
old_version=0
old_subver=0
[[Host.Content]]
range="A"
address="192.168.1.12"
port=3690
enbale=true
[[Host.Content]]
range="B~D"
address="192.168.1.13"
enbale=true
port=3690
[[Host.Content]]
range="E~Zz"
address="192.168.1.14"
enbale=true
port=3690
[[Host.Content]]
range="aA~zz"
address="192.168.1.15"
enbale=true
port=3690
